[features]
seeds = false
skip-lint = false
[programs.localnet]
basic_ownership = "AtJQsbbEmsKRAsTN3bAfwpLn3w6gYDwMwerJVqTv1AJD"
[programs.devnet]
basic_ownership = "AtJQsbbEmsKRAsTN3bAfwpLn3w6gYDwMwerJVqTv1AJD"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "localnet"
cluster = "devnet"
wallet = "/home/ylgr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/basic_ownership.json app/src/idl/basic_ownership.json"
